entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: "ctoacademy.io.vn"
            sans:
              - "*.ctoacademy.io.vn"
certificatesResolvers:
  letsencrypt:
    acme:
      email: "thanhnguyent472003@gmail.com"
      storage: "/letsencrypt/acme.json"
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
providers:
  docker:
    exposedByDefault: false
